/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSyncRouteRouteImport } from './routes/api/sync/route'
import { Route as ApiOrdersRouteRouteImport } from './routes/api/orders/route'
import { Route as ApiBotsRouteRouteImport } from './routes/api/bots/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOrdersCompleteRouteRouteImport } from './routes/api/orders/complete/route'
import { Route as ApiOrdersClearRouteRouteImport } from './routes/api/orders/clear/route'
import { Route as ApiOrdersIdRouteRouteImport } from './routes/api/orders/$id/route'
import { Route as ApiBotsIdRouteRouteImport } from './routes/api/bots/$id/route'
import { Route as ApiAuthLoginRouteRouteImport } from './routes/api/auth/login/route'
import { Route as ApiBotsIdClaimRouteRouteImport } from './routes/api/bots/$id/claim/route'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRouteRoute = ApiSyncRouteRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRouteRoute = ApiOrdersRouteRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsRouteRoute = ApiBotsRouteRouteImport.update({
  id: '/api/bots',
  path: '/api/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersCompleteRouteRoute = ApiOrdersCompleteRouteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ApiOrdersRouteRoute,
} as any)
const ApiOrdersClearRouteRoute = ApiOrdersClearRouteRouteImport.update({
  id: '/clear',
  path: '/clear',
  getParentRoute: () => ApiOrdersRouteRoute,
} as any)
const ApiOrdersIdRouteRoute = ApiOrdersIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOrdersRouteRoute,
} as any)
const ApiBotsIdRouteRoute = ApiBotsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBotsRouteRoute,
} as any)
const ApiAuthLoginRouteRoute = ApiAuthLoginRouteRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsIdClaimRouteRoute = ApiBotsIdClaimRouteRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => ApiBotsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/bots': typeof ApiBotsRouteRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteRouteWithChildren
  '/api/sync': typeof ApiSyncRouteRoute
  '/api/auth/login': typeof ApiAuthLoginRouteRoute
  '/api/bots/$id': typeof ApiBotsIdRouteRouteWithChildren
  '/api/orders/$id': typeof ApiOrdersIdRouteRoute
  '/api/orders/clear': typeof ApiOrdersClearRouteRoute
  '/api/orders/complete': typeof ApiOrdersCompleteRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bots/$id/claim': typeof ApiBotsIdClaimRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/bots': typeof ApiBotsRouteRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteRouteWithChildren
  '/api/sync': typeof ApiSyncRouteRoute
  '/api/auth/login': typeof ApiAuthLoginRouteRoute
  '/api/bots/$id': typeof ApiBotsIdRouteRouteWithChildren
  '/api/orders/$id': typeof ApiOrdersIdRouteRoute
  '/api/orders/clear': typeof ApiOrdersClearRouteRoute
  '/api/orders/complete': typeof ApiOrdersCompleteRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bots/$id/claim': typeof ApiBotsIdClaimRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/bots': typeof ApiBotsRouteRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteRouteWithChildren
  '/api/sync': typeof ApiSyncRouteRoute
  '/api/auth/login': typeof ApiAuthLoginRouteRoute
  '/api/bots/$id': typeof ApiBotsIdRouteRouteWithChildren
  '/api/orders/$id': typeof ApiOrdersIdRouteRoute
  '/api/orders/clear': typeof ApiOrdersClearRouteRoute
  '/api/orders/complete': typeof ApiOrdersCompleteRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bots/$id/claim': typeof ApiBotsIdClaimRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/bots'
    | '/api/orders'
    | '/api/sync'
    | '/api/auth/login'
    | '/api/bots/$id'
    | '/api/orders/$id'
    | '/api/orders/clear'
    | '/api/orders/complete'
    | '/api/auth/$'
    | '/api/bots/$id/claim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/bots'
    | '/api/orders'
    | '/api/sync'
    | '/api/auth/login'
    | '/api/bots/$id'
    | '/api/orders/$id'
    | '/api/orders/clear'
    | '/api/orders/complete'
    | '/api/auth/$'
    | '/api/bots/$id/claim'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/bots'
    | '/api/orders'
    | '/api/sync'
    | '/api/auth/login'
    | '/api/bots/$id'
    | '/api/orders/$id'
    | '/api/orders/clear'
    | '/api/orders/complete'
    | '/api/auth/$'
    | '/api/bots/$id/claim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiBotsRouteRoute: typeof ApiBotsRouteRouteWithChildren
  ApiOrdersRouteRoute: typeof ApiOrdersRouteRouteWithChildren
  ApiSyncRouteRoute: typeof ApiSyncRouteRoute
  ApiAuthLoginRouteRoute: typeof ApiAuthLoginRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots': {
      id: '/api/bots'
      path: '/api/bots'
      fullPath: '/api/bots'
      preLoaderRoute: typeof ApiBotsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/complete': {
      id: '/api/orders/complete'
      path: '/complete'
      fullPath: '/api/orders/complete'
      preLoaderRoute: typeof ApiOrdersCompleteRouteRouteImport
      parentRoute: typeof ApiOrdersRouteRoute
    }
    '/api/orders/clear': {
      id: '/api/orders/clear'
      path: '/clear'
      fullPath: '/api/orders/clear'
      preLoaderRoute: typeof ApiOrdersClearRouteRouteImport
      parentRoute: typeof ApiOrdersRouteRoute
    }
    '/api/orders/$id': {
      id: '/api/orders/$id'
      path: '/$id'
      fullPath: '/api/orders/$id'
      preLoaderRoute: typeof ApiOrdersIdRouteRouteImport
      parentRoute: typeof ApiOrdersRouteRoute
    }
    '/api/bots/$id': {
      id: '/api/bots/$id'
      path: '/$id'
      fullPath: '/api/bots/$id'
      preLoaderRoute: typeof ApiBotsIdRouteRouteImport
      parentRoute: typeof ApiBotsRouteRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/$id/claim': {
      id: '/api/bots/$id/claim'
      path: '/claim'
      fullPath: '/api/bots/$id/claim'
      preLoaderRoute: typeof ApiBotsIdClaimRouteRouteImport
      parentRoute: typeof ApiBotsIdRouteRoute
    }
  }
}

interface ApiBotsIdRouteRouteChildren {
  ApiBotsIdClaimRouteRoute: typeof ApiBotsIdClaimRouteRoute
}

const ApiBotsIdRouteRouteChildren: ApiBotsIdRouteRouteChildren = {
  ApiBotsIdClaimRouteRoute: ApiBotsIdClaimRouteRoute,
}

const ApiBotsIdRouteRouteWithChildren = ApiBotsIdRouteRoute._addFileChildren(
  ApiBotsIdRouteRouteChildren,
)

interface ApiBotsRouteRouteChildren {
  ApiBotsIdRouteRoute: typeof ApiBotsIdRouteRouteWithChildren
}

const ApiBotsRouteRouteChildren: ApiBotsRouteRouteChildren = {
  ApiBotsIdRouteRoute: ApiBotsIdRouteRouteWithChildren,
}

const ApiBotsRouteRouteWithChildren = ApiBotsRouteRoute._addFileChildren(
  ApiBotsRouteRouteChildren,
)

interface ApiOrdersRouteRouteChildren {
  ApiOrdersIdRouteRoute: typeof ApiOrdersIdRouteRoute
  ApiOrdersClearRouteRoute: typeof ApiOrdersClearRouteRoute
  ApiOrdersCompleteRouteRoute: typeof ApiOrdersCompleteRouteRoute
}

const ApiOrdersRouteRouteChildren: ApiOrdersRouteRouteChildren = {
  ApiOrdersIdRouteRoute: ApiOrdersIdRouteRoute,
  ApiOrdersClearRouteRoute: ApiOrdersClearRouteRoute,
  ApiOrdersCompleteRouteRoute: ApiOrdersCompleteRouteRoute,
}

const ApiOrdersRouteRouteWithChildren = ApiOrdersRouteRoute._addFileChildren(
  ApiOrdersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiBotsRouteRoute: ApiBotsRouteRouteWithChildren,
  ApiOrdersRouteRoute: ApiOrdersRouteRouteWithChildren,
  ApiSyncRouteRoute: ApiSyncRouteRoute,
  ApiAuthLoginRouteRoute: ApiAuthLoginRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
