module.exports = {
  UTC_OFFSET_MS: 8 * 60 * 60 * 1000, // UTC+8
  ORDER_COUNTER_START: 100,
  BOT_COUNTER_START: 1,
  ORDER_PROCESS_MS: 10000,            // 10 seconds per order
  SERVER_PORT: 3000,
  ORDER_TYPE: { NORMAL: 'NORMAL', VIP: 'VIP' },
  ORDER_STATUS: { PENDING: 'PENDING', PROCESSING: 'PROCESSING', COMPLETE: 'COMPLETE' },
  BOT_STATUS: { IDLE: 'IDLE', PROCESSING: 'PROCESSING' },
};
