name: backend-verify-result

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches: [ main ]

jobs:
  verify-result:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.9'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.19.0'

    - name: Verify Go version
      run: go version

    - name: Verify Node.js version
      run: node --version

    - name: Verify npm version
      run: npm --version

    - name: Make scripts executable
      run: chmod +x scripts/test.sh scripts/build.sh scripts/run.sh

    - name: Execute build script
      run: ./scripts/build.sh

    - name: Execute test script
      run: ./scripts/test.sh
