name: Deploy Vite Site

on:
  push:
    branches: [main] # Runs every time you push to main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Tells GitHub to host the 'dist' folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4